# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
      react-dnd:
        patterns:
          - 'react-dnd'
          - 'react-dnd-html5-backend'
      babel:
        patterns:
          - '@babel/*'
      linaria:
        patterns:
          - '@linaria/*'
          - '@wyw-in-js/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
